# -*- coding: utf-8 -*-
"""Day_1_task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16gi_HJMHEnR2hYLGyTcTpyv7LSRDQJiL

Download the dataset from [here](https://drive.google.com/file/d/1dVbihPJFSh6sqUkOZBQHyTFZBHPowLPc/view?usp=sharing)
"""

import numpy as np
import pandas as pd

data=pd.read_csv('/ecommerce.csv')

"""**Check the head of the DataFrame.**"""

data.head(5)

"""** How many rows and columns are there? **"""

data.info()

"""** What is the average Purchase Price? **"""

data['Purchase Price'].mean()

"""** What were the highest and lowest purchase prices? **"""

data['Purchase Price'].max()

data['Purchase Price'].min()

"""** How many people have the job title of "Lawyer" ? **

"""

data[data['Job']=='Lawyer']['Job'].count()

"""** How many people made the purchase during the AM and how many people made the purchase during PM ? **


"""

AM=0
PM=0
for i in data['AM or PM']:
  if i=='AM':
    AM+=1
  if i=='PM':
    PM+=1
print('PM\t',PM,'\nAM\t',AM)

data['AM or PM'].value_counts(dropna = True)

"""** What are the 5 most common Job Titles? **"""

(data['Job'].value_counts(dropna = True)).head(5)

"""** Someone made a purchase that came from Lot: "90 WT" , what was the Purchase Price for this transaction? **"""

data[data['Lot']=='90 WT']['Purchase Price']

d=data['Lot']
k=0
for i in d:
  
  if i=='90 WT':
    break
  k+=1
k
p=data['Purchase Price']
p[k]
d[k]
print(k,'\t',p[k])

"""** What is the email of the person with the following Credit Card Number: 4926535242672853 **"""

data[data['Credit Card']==4926535242672853]['Email']

"""** How many people have American Express as their Credit Card Provider *and* made a purchase above $95 ?**"""

data[(data['CC Provider']=='American Express') & (data['Purchase Price']>95)]['Purchase Price'].count()

"""** Hard: How many people have a credit card that expires in 2025? **"""

temp=pd.DataFrame(data['CC Exp Date'].apply(lambda x : int(x.split('/')[1])))
temp
temp[temp['CC Exp Date']==25].count()

"""** Hard: What are the top 5 most popular email providers/hosts (e.g. gmail.com, yahoo.com, etc...) **"""

data['Email'].apply(lambda x :(x.split('@')[-1])).value_counts().head(5)

"""# Great Job!"""